DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TRIGGER IF EXISTS order_updated_at_trigger ON "order" CASCADE;
DROP FUNCTION IF EXISTS update_updated_at() CASCADE;
