version: '3.8'

services:
#  db:
#    restart: always
#    image: postgres:latest
#    volumes:
#      - ./.database/postgres/data:/var/lib/postgresql/data
#      - ./db/umlaut/migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      - POSTGRES_PASSWORD=1474
#    ports:
#      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
