port: "8000"

nats:
  clusterID: "test-cluster"
  clientID: "client-123"
  subject: "foo"
  url: "nats://localhost:4222"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "wb"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  db: "0"

cors:
  origins: [
    "http://localhost:8000",
  ]
  methods: [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "OPTIONS"
  ]
  headers: [
    "*"
  ]
