db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "1474"

redis:
  addr: "localhost:6379"
  db: "0"

cors:
  origins: [
    "http://localhost:8000",
  ]
  methods: [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "OPTIONS"
  ]
  headers: [
    "*"
  ]
