redis:
  addr: "localhost:6379"
  db: "0"

cors:
  origins: [
    "http://localhost:8000",
  ]
  methods: [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "OPTIONS"
  ]
  headers: [
    "*"
  ]
